### ISSUE TITLE
Add language to user's profile

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/portal16#1402]
Add an editable optional field 'locale' to the user's profile. Display the UI according to the selected language.
~~Format 2 letters code (ISO 639-1).~~
Format BCP-47
Related to gbif/registry#213

**Comment by MortenHofft** [comment]
This might already have been discussed and I just missed the discussion. If so, then I do not want to open it again.

But I'm confused about what our prefered language codes are these days. And perhaps it doesn't have to be the same.

* We have 3 letter in the enum API http://api.gbif.org/v1/enumeration/basic/Language
* 2 letter, 3 letter and locale in https://api.gbif-uat.org/v1/vocabularyLanguage (btw @marcos-lg can 2 letter codes really be 3 letters long?)
* The website use 2 letter with an optional country qualifier to capture traditional vs simplified chinese.
* The registry use 3 letters for dataset language

With 2 and 3 letters language codes we cannot capture traditional vs simplified chinese. I do not know how much we intend to capture with these codes. Should we use something like BCP-47 instead of ISO 639-1?
I'm confused about where scripts recides - is it a part of language or locale or something else? As I understand it, writing system and country/regional variation in speech belong in the language code.

**Comment by mike-podolskiy90** [comment]
@MortenHofft let's use BCP-47 then. Matt tested that and it seems it suits us well

**Comment by mike-podolskiy90** [comment]
Backend functionality is on dev now

**Comment by mike-podolskiy90** [comment]
User's locale stored in the 'settings' field
