### ISSUE TITLE
derivedDataset page

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1444]
We need a page for the new derivedDatasets. Basically they could/should look like downloads as they have more or less the same structure—except for predicates.

Example: https://api.gbif-dev.org/v1/derivedDataset/10.21373/dd.kt3yec

Mock-up:

<img width="784" alt="Screenshot 2020-11-20 at 10 56 39 1" src="https://user-images.githubusercontent.com/21358085/99788778-e6bd1a80-2b21-11eb-8868-a50e21916ba8.png">

**Comment by timrobertson100** [comment]
In addition, we need a form that logged in users can post the file and generate a derived dataset. The API is [documented](https://github.com/gbif/registry/blob/master/docs/derived-dataset.md)

**Comment by ManonGros** [comment]
We need to also display the original DOIs when available (if this is a filtered version of a GBIF download - see this example: https://doi.org/10.15468/dd.jskxae)

**Comment by MortenHofft** [comment]
How will these appear in the literature feed? How to find out how often it has been cited?
For downloads we use the gbif key, but that doesn't exist here. Is it a new field?

**Comment by dnoesgaard** [comment]
Good question, hadn't thought of that.

**Comment by MortenHofft** [comment]
And related - how are these linked to the datasets?

I see that https://api.gbif.org/v1/derivedDataset/10.15468/dd.jskxae [use data](https://api.gbif.org/v1/derivedDataset/10.15468/dd.jskxae/datasets) from [Naturalis Biodiversity Center (NL) - Mammalia](https://www.gbif.org/dataset/009a76f6-0960-4a56-a116-63991e6bb037)

But I do not see the derivedDataset in the list of downloads
https://api.gbif.org/v1/occurrence/download/dataset/009a76f6-0960-4a56-a116-63991e6bb037?limit=500
(the data is currently included so I expect it would appear in that list of latest 500).

Is there another endpoint to get the derivedDatasets (instead of downloads) associated with a dataset?

**Comment by dnoesgaard** [comment]
- [ ] <title> should be Derived dataset, not download
- [ ] We should probably have a little symbol on the "See source" button as it is external
