### ISSUE TITLE
Tests: CMS content

### ISSUE THREAD

**Issue by burkeker** [gbif/portal16#148]
- [x] server side: test image URLs in markdown and HTML are converted correctly.
- [x] data model: test the integrity of related project content of BID programme - all projects should have grantType.
- [x] client side e2e test: search 'BID' will show BID in the feature block and clicking it will lead to programme landing page.

**Comment by burkeker** [comment]
@timrobertson100 @MortenHofft when you have time, could you please review these tests?

28be9ecb9d0e059a56bce1cc6f36f8b888a2bfe1
7f14ea0b4dba326a2ed8138d248945407d32d124
cdbd6ce2edf49f6fe0aff16e4e06e12eba471d57

If they are good, I'll apply the practice to more components on our project.

**Comment by MortenHofft** [comment]
Hi Burke
I see that the issue is closed, but I just looked briefly anyhow. I have some comments

1) there is references to your local machine bko
https://github.com/gbif/portal16/blob/4e5b651c2f6f22da6a6c437bbef48f20239176e5/app/helpers/cmsUrlEncode.js#L14

2) Why have a switch statement with dependencies on environments. Why not have one regex to encapsulate them all?
something a la: 
]\(http:\/\/([a-z]+\.)?gbif(-[a-z]*)?\.org\/sites\/default\/files\/.*\.png\)

3) Testing is difficult I find as it easily become half hearted alibis.

I’m not sure how you intend to use the function “extractAndEncodeUriMarkdown” https://github.com/gbif/portal16/blob/4e5b651c2f6f22da6a6c437bbef48f20239176e5/app/helpers/cmsUrlEncode.js#L10

But it seem to be intended to parse full markdown files. How about testing with some more text? You tests are a small syntactical invalid extract from a markdown file.

How about some more realistic tests? I imagine that will show some issues. Just looking at it it seem to me to have issues with

* two images. It look to me like that wouldn’t work for example.
* This will rewrite all links as well won’t it? Is that what you want?
* Will make a link to a pdf into a link to an image of a pdf - that seems wrong.

**Comment by MortenHofft** [comment]
https://github.com/gbif/portal16/commit/7f14ea0b4dba326a2ed8138d248945407d32d124

Hmm, I’m not sure what to think of this. It is a bit odd.
It asks for data from an external API and then tests that the data fields values.

One could argue that:

Either it is a part of the contract with the API, and then the test should be on the Drupal side as it is the API’s responsibility

Or: we do not know what we get, and the renderer should degrade gracefully if the data isn’t in that format (f.x showing “NOT PROVIDED” if that field isn’t there).

Assume that the API data changes after the test was run. If you rely on the data being in this format the page will still fail somehow - so you are in the same situation as before the test.

**Comment by burkeker** [comment]
Thanks, @MortenHofft .

For https://github.com/gbif/portal16/issues/148#issuecomment-263830161

- point 1 & 2, I've revised the regex as suggested ff9042c38aab5d0d79f49c68d99214fe50d46076. The intention is to test the image URL prefixing against markdown coming from the CMS API. So usually it comes as a piece of text, rather than as a file, and being in JSON, line-ending character is also escaped. To address your concern, I've used the text from our generic type pages in a static mock file for the testing purpose. I don't see anything preventing this function from being used on a longer text.
- It does prefix all image URLs in the given text, as the "g" flag suggests. If you have a look at the raw value and the converted markdown properties you will see the both image URLs are converted: https://demo.gbif-dev.org/generic/tools/species-population
- This won't rewrite all links, only those ending in the specified file extensions.
- You're right. I've excluded PDF from the types to search for.

For https://github.com/gbif/portal16/issues/148#issuecomment-263843170

The reason why we previously see unmatched columns in the BID project table was that some projects were expectedly exposed regardless their public status. An update on the API side fixed it, but I picked it as an example for writing test. I've changed this to the client side that validates the related project items to make sure they all have grant type specified, and if it comes as "null", "Not specified" will be shown instead of omitting the <td> element which causes broken table.

Hope this addresses. Thanks for useful comments.

**Comment by MortenHofft** [comment]
For the reasons I have already listed I still think it wont work @burkeker - I suggest you write some more tests - but maybe I'm misunderstanding the use case.

**Comment by burkeker** [comment]
This use case is rather limited in getting inline links in the existing CMS contents to be correctly prefixed. And I think you're right that more complicated situation will need improved regex to catch them. For that, I've created #183 to work on later. I provided description for existing case. fd69e419f421daafbfa79b43f7383150aaf58257

For improved e2e test I've committed them 4788d4a7c326a97dfc2f9d04f2ea5ecb2505606c.
