### ISSUE TITLE
Embedded video not displaying

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#149]
Trying to display video of dhobern's 2016 'History of GBIF' presentation on [What is GBIF?](https://demo.gbif-dev.org/generic/what-is-gbif), but video doesn't appear. Will not block closing out Issue #88, but it would be nice to include. 

iframe code persists in body content, so I think the Markdown just isn't rendering it:

> <iframe width="560" height="315" src="https://www.youtube.com/embed/ZnaoS_S7fMU" frameborder="0" allowfullscreen></iframe>

**Comment by MortenHofft** [comment]
My bad - i only allow a select few tags to avoid XSS attacks from publishers. I will create trusted sanitizer for cms content

**Comment by burkeker** [comment]
@MortenHofft  did you just say it works?

I thought I've documented the usage of the video embedding after the demo in summer to KC and DN. Assuming it's buried somewhere in a closed issue, and since this issue will be closed someday, I've created a wiki page [here](https://github.com/gbif/portal16/wiki/Notes-for-editors) to capture some usages.

I'll keep updating this page when appropriate.

**Comment by burkeker** [comment]
Meanwhile, we haven't changed the rest of content type rendering in Markdown yet. So for other content types that are not generic, iframe will still be exposed from Drupal, which has to be trusted indeed.

**Comment by MortenHofft** [comment]
closed with https://github.com/gbif/portal16/commit/60a25a6001a5c7703602d54acca121c3e81793b8#diff-27e4da4a3b532c654d0f6ae641c22213R41
