### ISSUE TITLE
Species search: add search to higher taxon

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#1508]
It seems reasonable to allow users to search for a higher taxon and not just select one from the facets.

Related https://github.com/gbif/portal-feedback/issues/3346

**Comment by MortenHofft** [comment]
Suggest do not work across datasets - so it is only possible to do so for the backbone

has results when datasetKey is set
http://api.gbif.org/v1/species/suggest?limit=10&q=Plantae%20Haeckel&datasetKey=a6c6cead-b5ce-4a4e-8cf5-1542ba708dec

No results without datasetKey
http://api.gbif.org/v1/species/suggest?limit=10&q=Plantae%20Haeckel

I guess no datasetKey is the same as backbone only?

**Comment by mdoering** [comment]
It is intended, but I am not convinced it is great. 

If you would allow suggest to work across datasets you would get back _Animalia_ a thousand times. That would be rather useless. And having a filter on higher taxon will always be for a specific dataset only. Otherwise we would need an additional search field that contains the matching backbone keys for each non backbone higher taxon. That would allow higher taxon search across datasets like we have for occurrences. But we would then miss all higher taxa that can't be matched and also the names that miss a higher classification alltogether. If you have plants names, but no kingdom, a search for kingom=plants would not yield them. Probably still a nice thing to have.

**Comment by MortenHofft** [comment]
It would be odd in the UI either way I agree. I think a solution could be to add it only when there is exactly one dataset. For now I can add it for the backbone. That is a simple improvement.

**Comment by mdoering** [comment]
@MortenHofft has this been done? I cannot see any higher taxon suggest in the portal, but I miss it to be honest. 
Could we add that for the simple search and in case the dataset facet is selected for a single datasetKey? That would make the higher taxon facet much more useable. Right now I have to do a name search to find out the higher taxon id and then manually replace the higher taxon key filter with that other id. I doubt many users do that

**Comment by mdoering** [comment]
Doh, I must have missed this somehow because I mostly use the advanced search, even when the dataset is restricted to the backbone. Would it be difficult to also add this to advanced search whenever a single dataset is selected?

**Comment by MortenHofft** [comment]
It is fairly awkward yes, that is why I didn't add it when I did so for the backbone. But if it is important, then I will find a way. It just isn't a 15 minute task. Let me look at it again.

**Comment by mdoering** [comment]
I might be the only user, but I will be a real user of that functionality ;)

**Comment by MortenHofft** [comment]
You will be the only user I'm sure, but I believe you are correct that more would benefit from using it. But as with so many of our functionalities, no one knows that they are there. Despite that they could be really useful. But that is a separate discussion.
