### ISSUE TITLE
Infrastructure: Setup internal only site

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#16]
The portal16 should be available on a deployment using LIVE or UAT data and CMS APIs, but be accessible only to GBIFS staff.  This should only run the released code, leaving the dev environment to be the continuous build and deploy version.

**Comment by MattBlissett** [comment]
I've set up a new Centos 7 server, from Ansible scripts, running only this portal.  It's accessible internally/VPN at http://uatnode-vh.gbif.org:3000/

Deploy using Jenkins, but change the parameters:

- TARGET_WEB_SERVER=uatnode-vh.gbif.org
- TARGET_WEB_DIRECTORY=/var/www/portal16
- TARGET_WEB_USER=jenkins-deploy

I've not done any more than that with Jenkins, since I don't know what the release process will be for this. The default remains to deploy to development.

The portal is deployed as the user `jenkins-deploy`, but runs as the user `portal16` without write access to its own files — just the log directory.

I'm not using the NodeJS `forever` module, since SystemD can restart a failed process itself — I've tested that this works.

Things I still need to do, for this to be done properly:
- [ ] Tidy up and commit Ansible scripts
- [ ] Implement whatever release process we decide upon
- [ ] Add a monitor to Nagios, using Ansible
- [ ] Build a devnode-vh.gbif.org server, so they're the same
- [ ] Find out what version of Node you wanted
- [ ] Give you SSH access to the server

This should probably be a new issue:
- [ ] Aim to get logs to go to Kibana

**Comment by MattBlissett** [comment]
Nagios monitor is here: http://aino.gbif.org/nagios/cgi-bin/extinfo.cgi?type=2&host=uatnode-vh&service=Check+HTTP — just checking port 3000 responds at the moment.

**Comment by MattBlissett** [comment]
http://devnode-vh.gbif.org:3000/ is now ready, please check it's OK.

It needs these settings for deployment:

* TARGET_WEB_SERVER=devnode-vh.gbif.org
* TARGET_WEB_DIRECTORY=/var/www/portal16
* TARGET_WEB_USER=jenkins-deploy

I've used Node v6, from RPMs rather than NVM.  I'd need to investigate why we should use NVM rather than Yum in this case, and change the Ansible scripts if we need to use NVM. (I'm not sure if NVM is something that should be used in production, or only development.)

All of use should have SSH access using the public keys you use for everything else, but your own username.  i.e. `ssh mhoefft@uatnode-vh.gbif.org`.  These users have permission to do things as root using `sudo`:

```
sudo systemctl status portal16
sudo systemctl restart portal16
```

**Comment by MattBlissett** [comment]
http://uatnode-vh.gbif.org:3000/ is now redone, as node.js v6.

**Comment by MattBlissett** [comment]
http://uatnode-vh.gbif.org:3000/ is now redone, as node.js v6.
