### ISSUE TITLE
Array field changes on the cluster page

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1770]
https://www.gbif.org/occurrence/1145095405/cluster isn't handling the recent changes for the array fields (datasetName and typeStatus I think are the only issues, but perhaps recordedBy etc might be too when expanded).

https://api.gbif.org/v1/occurrence/1145095405/experimental/related

**Comment by MortenHofft** [comment]
I think changing datasetName to an array is a mistake? As far as I remember datasetName shouldn't have been named so in the first place in the cluster API, but was done so because it was convinent somehow. It is really the datasetKey and datasetTitle I believe? That is how we have been using it at least

**Comment by MortenHofft** [comment]
preparations won't show as a list as it is shared with `;` as a separator. But that is a data issue of course

**Comment by timrobertson100** [comment]
datasetName was always whatever pipelines populated as the datasetName I can see, even when it was not an array.

I can join to the dataset table and pull the title if needed, but before I do, is it easy for the UI to show the title for the dataset, using the datasetKey?

**Comment by MortenHofft** [comment]
It is using the `publishingOrgName` name field. But I can either use GraphQL or write a proxy

**Comment by MortenHofft** [comment]
datasetnames fixed in https://github.com/gbif/portal16/commit/f000e8027953d20260947e94ac47a7e90bbcb5a0
