### ISSUE TITLE
Links from contentful getting messed up

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#1796]
On the [hosted portal page](https://www.gbif.org/hosted-portals?preview) contentful has the New Zealand link as https://www.gbif.org.nz but it becomes https://www.gbif.org/.nz/ on the site.

**Comment by MortenHofft** [comment]
I *think* i know why that is.

We rewrite links for multiple reasons. As far as I remember these:
* language versions (most important reason)
* links in contentful are often absolute. e.g. copied from the url, perhaps even from uat
* because the model sometimes require urls not just strings

so we rewrite links from Contentful to make them point to the correct environment and language version. Apparently that regex doesn't do a good job in this case.

I would think it was this function
https://github.com/gbif/portal16/blob/master/app/helpers/format.js#L232
