### ISSUE TITLE
Add programme filter to project (resource) search page

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#1872]
Hopefully this is an easy one :)

One this page:
https://www.gbif.org/resource/search?contentType=project

add filter/facet for Programme (e.g. show only programme=BID, etc.)

**Comment by MortenHofft** [comment]
So is that the programme acronym like in literature search?
https://www.gbif.org/resource/search?contentType=literature&gbifProgrammeAcronym=CESP

**Comment by dnoesgaard** [comment]
Yes, that's what we would like to be able to choose from in the filter.

**Comment by MortenHofft** [comment]
@fmendezh could we add the programme acronym to the ES projects index? I see that it is already in there in Contentful, we just do not include it for projects (it is there for the programme index itself).

**Comment by MortenHofft** [comment]
@fmendezh I just looked at the mapping and noticed that the projects index programmes as a nested field.
Since a project belongs to one programme only (that is correct is it not?) then the nested type seems overly complex. It makes querying more complicated, in a case where there is no need as far as I can see.

**Comment by MortenHofft** [comment]
Northern Eurasia  now have an acronym. I've added `required` and `unique` as constraints to the Contentful model.
