### ISSUE TITLE
Implement language specific CMS API

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#20]
Some articles are available in multiple languages. 

The CMS API needs to provide a means to indicate to the web layer that other languages exist for the same item.  There are various ways this can be achieved (either treating them as 1 entity with different representations, or multiple entities which are logically linked).  This needs considered design and should be presented before implementation.

**Comment by burkeker** [comment]
In the long run, the "one entity with different" representations should work better for us. In Drupal 7, it's achieved by making fields translatable, while logically they are attached to the same entity. When we only enable translation for the required fields, it's more storage efficient. This is also the way [Contentful handles locale](https://www.contentful.com/developers/docs/concepts/locales/
).

Once a translated version is provided, and if we determine the language by URL, it's the prefix of URL alias to indicate the locale. For example, `fr/newsroom/news/first-bid-grants-for-africa` is the French version of `newsroom/news/first-bid-grants-for-africa`. However, once a visitor navigate to `fr/*`, all of the links on the page will be prefixed with language code, and from there one will be navigating under `fr/*` until an entity is available in other languages which will offer an opportunity to switch, or an universal language switcher is implemented so visitors can change anytime. On our site this doesn't do much since most of the prefixed URL will fallback to provide English content, but the prefix in the URL is the confusing bit.

Going down this 'ideal' way is not technically expensive (max 2 days of work), but having URL prefixed with language codes implies the readiness of a fully functioning multilingual site which will involve more content work. Therefore for now we'd go for a temporary solution.

As a temporary solution, we will create an entity reference field for translated entities to refer to the English original. And when each of these entities are requested, it's the underlining queries to inform the availability of other versions.

**Comment by burkeker** [comment]
Use http://cms.gbif-dev.org/api/v1/news/82784 as an example, once the references of its translations are set using `field_translation_source`, in the normal news output we have
```
translated_copies: [
{
id: 82787,
type: "news",
language: "pt"
},
{
id: 82789,
type: "news",
language: "fr"
}
]
```
as part of the `__system` attribute.

When a locale is provided http://cms.gbif-dev.org/api/v1/news/82784?locale=fr, the French version is given, with 
```
translationSource: [
{
id: 82784,
type: "news",
created: "1465889220",
title: "First BID grants provide nearly €1 million in funding to 23 African projects",
language: "en"
}
]
```
indicating the English original.

If a localized version doesn't exist for the node, http://cms.gbif-dev.org/api/v1/news/82784?locale=de, the system simply outputs the entity with the indicated `id`.

**Comment by burkeker** [comment]
We may need to revisit this when the language routing are being implemented in Express.
