### ISSUE TITLE
Correct terminology of species populations

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#200]
**Correct terminology of species populations**

**THIS NEEDS REVIEW FROM @dschigel BEFORE IMPLEMENTATION**

Thanks to detailed feedback from DS and SM, we should rename this as follows:

-  [ ] menu item should read &quot;Relative abundance trends&quot;
-  [ ] the URL should be /tools/relative-abundance-trends 
-  [ ] the embed URL should be /embed/relative-abundance-trends 
-  [ ] the information URL of the tool should be /tools/relative-abundance-trends/about
-  [ ] the title of the tool should read &quot;Relative Abundance Trends&quot;
-  [ ] the statement should read &quot;Visualise the rate of change of relative abundance of a species over time.&quot;

-----
fbitem-f0b1d8e8c6811b830ef2f932fb5cf1be7ba9cf0a
Reported by: @timrobertson100
System: Chrome 54.0.2840 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/tools/species-population
Window size: width 1433 - height 799

**Comment by dschigel** [comment]
Hello,

Following the Science Committee visit and comments by Anders Finstad <anders.finstad@ntnu.no> (who can be contacted for clarification if needeed), replace "abundance" with "occurrence" in all cases above, such as Relative occurrence trends. I did some Google scholar after the discussions and there is such an idiom, which is accurately describing what tool is doing (in contrast with measuring abundance in ecology)

**Comment by timrobertson100** [comment]
Thanks @dschigel 
Can you post a couple of the links that we could reference in the tool description on that please?

**Comment by dschigel** [comment]
The change of name is requested by Anders, I don't know what is his reason for suggesting that, I guess it's his expertise, so I suggest we use SC minutes what the document is archived by admin. We discussed it on day II of the SC meeting, so SC recommendation should be enough grounds for the change. We could wait for minutes approval by SC.

It is an intuitive and accurate name, to find some uses cases I just did Google Scholar for relative occurrence trends and checked the first 10-20 hits https://scholar.google.fi/scholar?hl=en&q=relative+occurrence+trends&btnG=&as_sdt=1%2C5&as_sdtp=, some from medical, some from biodiversity science, I cannot see a single reference we can safely use in "as used by NN, YYYY." I have a book on my desk where PSI, population size index was measured similarly for the Swedish longhorn beetles, but it's a bit different thing. Since this is a rather special way to deal with occurrence data, we could as well give GBIF's own definition in the tool description here https://demo.gbif.org/tools/species-population/about

**Comment by ahahn-gbif** [comment]
Don't want to disrupt any more important work, but as this is labeled as "easy gain", would there be a chance to still add these changes before the GLOBIS-B meeting (March 20-22), to avoid unnecessary discussions around misunderstandings caused by the name?

**Comment by MortenHofft** [comment]
These are corrected based on a mail sent by Dmitry, signed by Donald Friday 7 April 2017
