### ISSUE TITLE
"what is gbif" page returns 404

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#212]
When going to https://demo.gbif.org/what-is-gbif one is redirected to
https://demo.gbif.org/generictemplate/what-is-gbif which is a 404

@burkeker I'm guessing you know exactly what this is so I'm assigning you

**Comment by burkeker** [comment]
Yes, I know what exactly is going on: part of the URL redirects are yet to be cleaned up...

**Comment by burkeker** [comment]
This is partially due to the change of deployment procedure that, when the URL rewriting is about to run, the command hasn't been available because the affiliating module is still being enabled.
This commit solves that: https://github.com/gbif/gbif-drupal/commit/826daf015f46ed8ceda00843b2238cb03d620c7f

**Comment by burkeker** [comment]
https://demo.gbif-dev.org/what-is-gbif
