### ISSUE TITLE
I prefer the old map!

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#214]
**I prefer the old map!**

The old map allowed for a rapid overview of the extent and data density of a species distribution. The hexagons in the new system are too large, and repeated in and out zooming is needed to achieve the same overview as before.
The initial map is also too small, especially if one is only trying rapidly gain an idea of multiple species tanges.
Otherwise, looks cool, although it&#39;s a shame the Gopher site doesn&#39;t work... ;)

-----
fbitem-species1201292
Reported by: phil.buckland@umu.se
System: Firefox 50.0.0 / Windows 7 0.0.0
Referer: https://demo.gbif.org/species/1201292
Window size: width 1216 - height 920

**Comment by MortenHofft** [comment]
Thank you for helping us improve the new site!

We still expect to do some work on the maps. We introduced the hexagons because we felt that they provided a better overview of the range including outliers. Especially for species/datasets with sparse data. There will still be an option to show the point data!

Some of the things that we have in our pipeline is supporting multiple projections and automatically zooming to the extend of the data. I believe that doing so will help with the issues you point out. As for range we are in dialog with IUCN about integrating their range maps as well.

**Comment by MortenHofft** [comment]
Map widget has been implemented and point maps as you know them are back. Thanks for your feedback
