### ISSUE TITLE
LInk to dataset homepage?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#219]
**LInk to dataset homepage?**

...a nice feature on the old portal was: LINKS
Dataset homepage, will it be implemetned here too?

-----
fbitem-dataset6867ae37-74b8-43e7-805d-5dac0a6d447e

System: Chrome 55.0.2883 / Windows 7 0.0.0
Referer: https://demo.gbif.org/dataset/6867ae37-74b8-43e7-805d-5dac0a6d447e
Window size: width 2048 - height 1024
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-06T14:47:59.285Z',mode:absolute,to:'2017-01-06T14:53:59.285Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-06T14:47:59.285Z',mode:absolute,to:'2017-01-06T14:53:59.285Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kbraak** [comment]
Comment copied over from https://github.com/gbif/portal-feedback/issues/22#issuecomment-

> +1 from me as well.
> 
> I initially suggested making the origin of the dataset more prominent on the dataset page of the new portal, because some publishers feel we don't do enough to redirect traffic to them. Traffic on their own website is important, otherwise their funders won't continue to sustain them. This is the case for Reef Life Survey for example, who has a [feature rich website](http://reeflifesurvey.com/) including several services for exploring and downloading their raw data. 
> 
> We should also keep in mind the publishers' own websites is where users can get the latest data (Reef Life Surver only publishes to GBIF biannually). The same can surely be said for eBird and other big projects.

**Comment by rdmpage** [comment]
If this is an issue for data providers then perhaps GBIF can also encourage providers to have stable URLs for individual records (some already do this). If these are available on individual occurrence records then that gives visitors to GBIF another chance to be directed to the source.

I also think we need data on this. It's easy to attach Google Analytic events to links, so GBIF could discover how many time people click on links to providers, and also whether placement of links affects how many people do click through.

**Comment by peterdesmet** [comment]
To further complicate the issue, there's a difference between:

1. **Dataset homepage** indicated in the metadata, which I understand is what this issue is about, e.g. https://waarnemingen.be/ This URL is important for PR and traffic.
2. **Source webpage** or the page where the source DwC-A can be found (known from the registry), e.g. http://data.inbo.be/ipt/resource?r=dagvlinders-natuurpunt-occurrences This URL is important for finding source data, which might include more than what GBIF is crawling, and which absolutely required for checklist datasets, as these cannot be downloaded from GBIF.

Both are shown on the current dataset homepage: http://www.gbif.org/dataset/1f968e89-ca96-4065-91a5-4858e736b5aa on the right, in the new implementation they are displayed in the tab "Origin": https://demo.gbif.org/dataset/1f968e89-ca96-4065-91a5-4858e736b5aa/origin. It makes sense to have them there, but I can see why some want one or both to be displayed more prominently. 😄

**Comment by MortenHofft** [comment]
Dataset home page is now promoted to the nav tabs bar instead of under Links in the sidebar
https://demo.gbif.org/dataset/1f968e89-ca96-4065-91a5-4858e736b5aa

the dwca is moved to the download button and repeated again in the bottom of the page

Please reopen if you believe that the various links, endpoints etc do not get the attention they deserve.

**Comment by peterdesmet** [comment]
Nice, good solution! I like that the dwca has moved to the download button. Have comment about that button, will discuss in separate issue.
