### ISSUE TITLE
Missing literature content?

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#236]
[This paper](http://dx.doi.org/10.1371/journal.pone.0142240) seems to be missing from [a literature search](https://demo.gbif.org/cms/search?q=HIT%20indexing) but is in the GBIF public library in Mendeley and tagged with things that suggest it should be available (e.g. `GBIF_author` `GBIF_primary` `GBIF_used`)

![screenshot 2017-01-18 13 29 50](https://cloud.githubusercontent.com/assets/237221/22064215/d62e94be-dd82-11e6-9d3d-2b5ff47511b7.png)

**Comment by timrobertson100** [comment]
This might be intended and not a bug, but it is a bit confusing.  
GBIF [currently have 2,427 results](https://demo.gbif.org/cms/search?type=literature) but the Mendeley GBIF public library has 4,274 papers (see screenshot above).

If it is intended, what are the rules for deciding if a paper is included please?

**Comment by burkeker** [comment]
We temporarily decided to only include journal articles which was lifted in the recent update since all types of curated documents in Mendeley are peer-reviewed. Together with the adjustment of the deployment, this document is now surfaced on the search result. From there, you can see tags are available as filter choices.

https://demo.gbif-dev.org/cms/search?q=B-HIT
