### ISSUE TITLE
Dataset metrics broken?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#237]
**Dataset metrics broken?**

Tried opening the metrics tab for eBird and a smaller dataset AlgaTerra, but in both cases all I see is: &quot;We couldn&#39;t compile the stats for this dataset. You&#39;re are welcome to get in touch.&quot; 

I expected to see a nice bar chart with download usage stats. Is it broken?

Additionally, the &quot;get in touch&quot; is a link opening an email addressed to helpdesk@gbif.org. Better this opens the Feedback dialog instead as this is intended as the primary mechanism for collecting feedback in the new portal. 

Thanks,
Kyle

-----
fbitem-dataset4fa7b334-ce0d-4e88-aaae-2e0c138d049e
Reported by: @kbraak
System: Firefox 50.0.0 / Mac OS X 10.10.0
Referer: https://demo.gbif.org/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e/metrics
Window size: width 1712 - height 775
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-18T11:37:24.070Z',mode:absolute,to:'2017-01-18T11:43:24.070Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-01-18T11:37:24.070Z',mode:absolute,to:'2017-01-18T11:43:24.070Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi Kyle - thanks for reporting it.

Going through the code it should originate in a 503 error from the APIs. It retries twice and waits 30 seconds for a response. if the server return 503 twice it fails and show that error message. But I do not see that error from the API in the logs.

I do not now exactly. The links work now but it is obviously flaky since you saw an error.
Thanks

**Comment by MortenHofft** [comment]
and nice point about the feedback by the way. that help text was written before we implemented a more structured feedback mechanism. Ideally it should also mention the system status once that endpoint is there.

**Comment by kbraak** [comment]
Thanks for following up on the issue. How about instead of inviting unnecessary feedback when we know our services are down or under heavy load, to instruct users to just wait and try again later? In a way this relates to https://github.com/gbif/portal16/issues/216 The help text definitely needs fixing though - do you need me to create a new issue for that since you closed this one? Thanks.

**Comment by MortenHofft** [comment]
that is exactly what #216 is for yes. You referencing as you have just done is enough i would think. basically this referring to the system status is something that applies to all failure feedback. And will also be a part of the feedback form. But for now we do not have it.

As long as we do not have that status, we cannot do anything but ask people to report the error. The exact wording should now be to ask the users to use the feedback form. How that is best conveyed in english I will leave to you.

this issue is not closed btw :)

**Comment by MortenHofft** [comment]
it was a simple timeout as it was set to 3 sec. I have increased it to 30sec https://github.com/gbif/portal16/commit/74df62a484d1c1a7e32da0ab9820cda97c3195b2, but it will block loading of the page. it should be moved to a async client call instead.

there is a directive for it already: https://github.com/gbif/portal16/blob/master/app/views/pages/country/key/datasetBreakdown/datasetBreakdown.nunjucks#L36

**Comment by MortenHofft** [comment]
I'm closing this Kyle as it was a timeout issue. And if we cannot generate the result within a minute or the API is down, it should show an error as it do. I will update the error to be more informative. And at some point all of those will be moved into translation files. 
If you see this issue again where you find that it doesn't make sense, then please reopen or ping me again. Thanks
