### ISSUE TITLE
Species taxonomy doesn't have a hierarchy

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#281]
@dschigel you reported the other day that species taxonomies presentations are broken and show a flat table of children. As I mentioned the other day, when e.g. a far lower rank has no parent in the rank just above, it will show as attach to the higher rank. So a species could be listed just under a kingdom.

Could you please specify and give an example of the bug here? I have difficulties evaluating these kind of bugs without some guidance. 

They look fine to me.
Example: http://www.gbif.org/species/2 and https://demo.gbif.org/species/2

**Comment by dschigel** [comment]
There were two issues we discussed simultaneously. I would like to use Aves as an example, because there are more taxa and more synonyms. Current portal has quite neat list of subordinate taxa, e.g. class Aves has a list of orders, but not of other lower level taxa with very few or no records and linked directly to Aves. Compare Subordinate taxa http://www.gbif.org/species/212 to https://demo.gbif.org/species/212, look for the long list of taxa after Trogoniformes - why those lower taxa with no or almost no records are there? Here is one example of problematic genus linked directly to Aves and no records https://demo.gbif.org/species/4851521. The list of "synonyms" of Aves is crazy at both portals, @mdoering - not sure what are those. Eupterornis remensis Lemoine, 1878 is defintely not a synonym to Aves.

Another, I think unconnected, issue discussed is the need, at some point, to present list of taxa both alphabetically and taxonomically sorted. Here is one https://demo.gbif.org/occurrence/search?taxon_key=212, and here another example https://demo.gbif.org/occurrence/search?taxon_key=212&geometry=POLYGON%20((21.09375%2012.886068614667776,%2054.140625%2029.830480872013204,%2071.71875%2047.746220628945906,%2041.484375%2061.433165651246526,%2023.203125%2046.792038780015524,%2023.90625%2033.42166334057351,%2021.09375%2012.886068614667776)) where these options would be very welcome.

The orders in the beginning of the list are fine in principle, so when I click Gaviiformes with 30 children I get https://demo.gbif.org/species/7192754, with one good family, and two suspicious cases, such as https://demo.gbif.org/species/4852113

**Comment by MortenHofft** [comment]
**1**
I still do not understand. This is a screenshot from the current portal of aves. Notice the data after Trogoniformes. I have no idea if this is correct or not, but it is the behaviour of the existing portal and the same on the new one as far as I can see. Am I misunderstanding something here?

![screen shot 2017-02-15 at 13 38 31](https://cloud.githubusercontent.com/assets/6759267/22974774/2cc4ed8e-f384-11e6-82af-0648dc623b86.png)

**2**
Yes this is another thing we also talked about. The option to sort occurrences is fine by me, but not supported by the API. I don't see it being something that is supported anytime soon, but that is really an issue for @fmendezh . If you believe it is important I suggest creating an issue and start a discussion at https://github.com/gbif/occurrence/issues . Once that is done, it is a small thing to implement it on the site.

**Comment by mdoering** [comment]
Yes, this is expected behavior in the API and current portal. We simply do not have known classification for all ranks and even genera get hooked directly under a kingdom sometimes.

So data wise this is ok and expected. But for the presentation I agree there might be better options. Ideally we would lump all other lower ranks of Aves into a single incertae sedis order. But this gets tricky and probably needs some serious backend changes. It also isnt strictly correct as it suggests all those families belong to the same unknown order which is not true. Open to improvments

**Comment by rdmpage** [comment]
I think there are at least two separate issues here. 

The first is that many of these lower taxa that are attached to "Aves" aren't taxa but names. I'd be a lot happier if GBIF's model clearly separated these. For example, _Addoeca_ http://www.gbif.org/species/4850543 is a genus name proposed by Matthews http://biostor.org/reference/114591/page/1 for the species _Microeca addita_. This species is now _Rhinomyias addita_ (see http://www.biodiversitylibrary.org/page/14484009 ) and so _Addoeca_ is a synonym of _Rhinomyias_. Because GBIF lacks this information it ends up as a "bird of some sort" and gets joined to Aves. The default assumption that every name is a taxon unless we have evidence otherwise leads to a very messy bird classification (ornithologists have created lots of extraneous genera). Many of these genera are names, not taxa.

The other issue is fossils, which are often poorly known and hence difficult to place. The record of _Eupterornis remensis_ comes from The Paleobiology Database  http://www.gbif.org/species/121516228 which cites "C. Mourer-Chauviré. 1994. A large owl from the Paleocene of France. Palaeontology 37(2):339-348" as a source. P. 346 of this paper http://biostor.org/reference/166051/page/8 basically says it might be a loon, but who knows? Somewhere along the line the assertion that "this is a bird" (http://fossilworks.org/?a=taxonInfo&taxon_no=202886) has been transmogrified into "it's a synonym of birds".

This isn't easy to sort out, but it does reflect badly on GBIF if a popular, data-rich group has such as messy and illogical classification. I think some sort of lumping and/or colour scheme to flag fossils and names (i.e., taxa with no children and no intermediate ranks between themselves and Aves) would help clarify things. Maybe even an option to filter these things out...?

**Comment by MortenHofft** [comment]
The data issues are beyond me, but I can help with the presentation. Links to everyones favourite taxonomy browser and how they handle similar issues would be much appreciated. Thanks

**Comment by dschigel** [comment]
For a quick display fix, I support lumping those problematic and paleo names into "other names" (not incertae sedis) category under it's parent taxon and next to the good children taxa: Class Aves -> orders, other names. Order Gaviiformes -> Family Gaviidae, other names. Names, not taxa, as @rdmpage points out. This mass grave solution will not fix it, but will result in substantially better look until the better data is available.

**Comment by mdoering** [comment]
If I follow this issue correctly I see at least 2 distinct issues:

1) **bad synonyms**: the current backbone indeed does create weird synonyms across higher ranks which should not be the case. This is captured in an older issue which has been adressed in the about to be released backbone version january 2017: http://dev.gbif.org/issues/browse/POR-3169
No Aves species or genus synonyms anymore: http://api.gbif-uat.org/v1/species/212/synonyms

2) **classification gaps**: for some taxa we simply don't have a complete classification. I would not necessarily say these are just names. We do treat them just the same as any other taxa. Nevertheless we have an outstanding issue with better interpreting the nomenclatural status of a name, so currently there are some cases when an invalid name is treated as an accepted or doubtful taxon. If the status is doubtful it should clearly be taken with caution. Maybe it is worth marking up doubtful names in the tree differently? As I said above creating an artificial bucket for lumping all other taxa at a lower rank makes sense to me from the presentation, but leaves some questions open to me: 

 - how to label this bucket, I am not convinced "other names" is good. These are not just names.
 - is it misleading to have one bucket grouping taxa that should not be grouped together at that rank? All direct Aves children at family level or below do not share the same unknown order.
 - is this bucket rendered client side only or also through our API? Does it need an id so you can link to it and show its contents? If API and ids are needed this likely needs serious code changes and a new backbone to be generated.

**Comment by dschigel** [comment]
1. Very nice
2. Can't we sort names by rank and then alphabetically within each rank?

The bucket could help visually and to me having than grouped or not is more or less the same. Incertae sedis could be an option but probably not 100% accurate too.

**Comment by mdoering** [comment]
@dschigel the rank then alphabetical name order is what we currently do. I call that "taxonomic order" in the checklistbank code and its used in many places as the default ordering.

**Comment by mdoering** [comment]
... maybe just a separator line or larger margin when a new "rank" block starts?

**Comment by rdmpage** [comment]
Maybe we can get some inspiration from how NCBI handles this sort of question, e.g. https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=8782

For the birds there are two additional kind of taxa that NCBI shows, "environmental samples" and "unclassified x" where "x" is a taxon name. 

![screenshot 2017-02-21 13 46 48](https://cloud.githubusercontent.com/assets/83306/23167456/492d4b08-f83c-11e6-8c3c-d25e28f3cb7a.png)

Environmental samples are a bit like saying, well its a bird but we've no idea what it is (actually if we looked at the sequences we probably could figure it out, but let's ignore that for the moment). In the "unclassified" category are things like DNA barcodes that are labelled to, say, family or ordinal level. Maybe we could do something similar with "unclassified", for example, at each node in the bird classification, if there are things that belong somewhere above that node but we don't know where, we could have a node called "unclassified x" where "x' is the current node in the classification (this way we have - mostly -unique names). This does raise issue of how to treat such nodes as they aren't really taxa, but it does give us a place to put them, and it does get them out of the way of the known groups.

**Comment by MortenHofft** [comment]
This has largely been redone. Everyone involved in the thread has seen it, and approved. There might be other issues, but those deserves new issues and are welcomed. I'm closing this. Thanks for your ideas. There are still some changes coming (italics for one).
