### ISSUE TITLE
Allow users to filter occurrences by recorder's ORCID

### ISSUE THREAD

**Issue by kbraak** [gbif/portal16#334]
This would enable users to reliably find all occurrences recorded by an individual, so long as that person's ORCID was entered properly in the right DwC term. Blocked by proposed DwC term addition [recordedByID](https://github.com/tdwg/dwc/issues/102)

Making ORCID a prominent occurrence filter will highlight its value to GBIF's users and publishers.

In the future, GBIF may allow a user to login using their ORCID account (#297). In this case, GBIF will be able to easily show the user a filtered list of all the occurrences that they have contributed to.

**Comment by dagendresen** [comment]
Remember that only currently alive researchers can get an ORCID (because the researcher need to create the ORCID herself/himself. Some of the specimen collectors we have in Norway are not currently alive. ORCID is a subset of ISNI numbers. Another good option collectors that cannot get an ORCID number, is the VIAF numbers - VIAF is rather a superset of ISNI numbers.

dwciri:recordedBy or a dwc:recordedByID would be a major improvement!

**Comment by dshorthouse** [comment]
I have an abstract submitted for @tdwg, Ottawa 2017 to propose a DwC extension for agents and  their roles. See also https://github.com/tdwg/dwc/issues/102 and https://github.com/tdwg/dwc/issues/101.

**Comment by timrobertson100** [comment]
Please see https://github.com/gbif/pipelines/issues/251

**Comment by timrobertson100** [comment]
Now live on GBIF.org 
[example](https://www.gbif.org/occurrence/gallery?recorded_by_id=https:~2F~2Forcid.org~2F0000-0001-6215-3617&advanced=1)
