### ISSUE TITLE
Dataset coverage shows wrong counts

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#339]
**Dataset coverage shows wrong counts**

The dataset coverage on a species page shows very different counts than on the linked dataset search. E.g. 100 vs 460 for Abies Mill. in occurrences and 34 vs 23 for checklists.

-----
fbitem-species2684876

System: Chrome 56.0.2924 / Mac OS X 10.12.3
Referer: https://demo.gbif.org/species/2684876
Window size: width 1639 - height 912
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-22T12:05:19.380Z',mode:absolute,to:'2017-03-22T12:11:19.380Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-03-22T12:05:19.380Z',mode:absolute,to:'2017-03-22T12:11:19.380Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
not a bug per se, but the counts on the species page is using the counts api instead of using SOLR. It is the exact same behaviour on the live site.

**Comment by MortenHofft** [comment]
from https://github.com/gbif/portal-feedback/issues/152

-----
Should use occurrence search service for counts, not metrics

This shows Occurrences: 8908939 which is the current value in the HBase cube (i.e. a ../metrics/.. API call) and inaccurate.

All occurrence counts must come from /occurrence/search calls because we plan to deprecate and remove the metrics service. This will be slower (i.e. use AJAX) but will be consistent.

Please check for existence of any call in the project making use of HBase cube tables. There are 3 tables (plus v1 maps) so first need to identify the API calls associated.

This should be considered a blocker for release.

fbitem-species2490384
Reported by: @timrobertson100
System: Chrome 57.0.2987 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/species/2490384
Window size: width 1440 - height 799
API log
Site log

**Comment by MattBlissett** [comment]
If we're deprecating the metrics calls, should we reimplement them as calls to SOLR?

There is a little external use of the metrics API, e.g. pygbif.

**Comment by timrobertson100** [comment]
Yes, we should if feasible or announce the deprecation and then remove.

**Comment by MortenHofft** [comment]
Given that this is the same behaviour as the current site and we don't have an API call to replace the metrics, I will remove blocker from this and make it an API issue

**Comment by MortenHofft** [comment]
The conflicting counts are not there, but the dependecy on the count API is still there. The taxon search part of the dataset search has been rolled back due to instability. A new issue has been created for the deprecation of count apis https://github.com/gbif/portal16/issues/523
