### ISSUE TITLE
Citizen science page missing

### ISSUE THREAD

**Issue by kcopas** [gbif/portal16#346]
Just spoke with Karen Soacha of SiB Colombia at the Citizen Science Association conference in the U.S., and had her ask where the [citizen science page](https://demo.gbif.org/citizen-science) on the new site went. Now I'm asking, too ;-)

I suspect it's a Drupal-to-Contentful related menu issue, no?

**Comment by kbraak** [comment]
@kcopas https://github.com/gbif/portal16/issues/86 indicates that was still a work in progress, is that true?

I had a similar question about the missing [infrastructure](http://www.gbif.org/infrastructure/summary) section. https://github.com/gbif/portal16/issues/226 indicates a decision is still pending how to show that content in the new portal? Any ideas? Thanks

**Comment by dnoesgaard** [comment]
Pages authored using the "generic content" template in Drupal were not part of the Drupal->Contentful import. Because the number is low, and content still needs to be revised, I've agreed to manually re-recreate these in Contentful. This affected pages such as "Data papers", "Contact us", "About GBIF", etc. but I've started bringing them back. CitSci page is next! ;)

**Comment by dnoesgaard** [comment]
https://demo.gbif.org/citizen-science is back up now. I've added a picture to keep it in line with the look of the other pages. Let me know if anything needs changing. Note that this content now _lives_ in Contentful and is not imported from Drupal.
