### ISSUE TITLE
Review case sensitivity handling for the user accounts

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#347]
This is really a `registry` issue, but we need to track it as a blocker with the UI for the identity management and hence created in this project.

It seems that username are case sensitive.  An account of `aus` (name changed) created in www.gbif.org was migrated as such but the user reported they cannot log in on the demo site with `Aus`.  

We should treat the username and email as case insensitive all over the [SQL](https://github.com/gbif/registry/blob/identity/registry-identity/src/main/resources/org/gbif/identity/mybatis/UserMapper.xml)

**Comment by cgendreau** [comment]
I think for the emails we can always use the lowercase version. We would have to run a sql update on the current content and lower case on insert, update and query.

For the username I'm not sure. If the user entered "Aus" maybe we want to keep it like that in the database and indeed just change the queries (SQL directly) so he can login with "aus". But, we would need to also change the INDEX and UNIQUE constraint .

**Comment by cgendreau** [comment]
fixed on the registry identity branch

**Comment by cgendreau** [comment]
For the record, the emails will be stored as provided (since only the domain is really case insensitive) but a constraint will be added on the lowercase version of the email field. In other words, we will store emails as is and they shall be unique based on their lowercase representation enabling us to allow login using the case insensitive version.
