### ISSUE TITLE
No link to IPT homepage displayed on IPT installation page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal16#488]
**No link to IPT homepage displayed on IPT installation page**

Only the RSS endpoint is currently displayed

-----
fbitem-96b9527ed3c47b4e8e65817ad1ca3f20236b567a
Reported by: @kbraak
System: Safari 10.1.2 / Mac OS X 10.10.5
Referer: https://www.gbif-uat.org/installation/b6bbcb00-d6a6-4c2b-a4a2-c70dbed7f188
Window size: width 1397 - height 801
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:28:41.586Z',mode:absolute,to:'2017-08-15T09:34:41.586Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:28:41.586Z',mode:absolute,to:'2017-08-15T09:34:41.586Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
The general principle has been to reflect the API in the interface. 

And since the API has the option to add a home page and more endpoints (for a website fx), then this seem to me like the place to add that information. If doing so it will show up as a website link on the installation page.

Adding a special rule in the website saying `if rss feed contains ipt then guess website` seems to me like adding clutter when the option to do it in the API exists already?

@kbraak what is the impact would you say of having this on the page?
@timrobertson100 what is your take - is this something that should go into the API? How do installations get registrered in the first place. Why not add the homepage there?

I'm not sure wether to consider this a bug or an idea.

**Comment by kbraak** [comment]
The homepage URL is essential for IPT installations, but not applicable to other types of installations. It will have a significant impact, as it will make it more convenient to open the IPT in order to do follow-ups, curation, etc.

It would be nice to display the IPT's RSS feed using the RSS icon. For the homepage, it would be nice to reuse the same icon as used for the dataset homepage.

**Comment by timrobertson100** [comment]
I'd suggest it sensible to do logic of "if type=IPT and has an RSS endpoint, construct a link to the homepage using the RSS endpoint but removing the trailing /rss.do".

That is what the current website does [in this line in the template](https://github.com/gbif/portal-web/blob/master/src/main/webapp/WEB-INF/pages/installation/detail.ftl#L38)

**Comment by MortenHofft** [comment]
Seems the wrong place to me, but it is now added
