### ISSUE TITLE
Feedback in portal-feedback not appearing on site

### ISSUE THREAD

**Issue by rdmpage** [gbif/portal16#504]
The README for https://github.com/gbif/portal-feedback says that issues raised via the feedback button and opened in https://github.com/gbif/portal-feedback will appear on the relevant page in gif.org. This doesn't seem to be happening (HT Tony Rees). For example, https://github.com/gbif/portal-feedback/issues/359 relates to https://www.gbif.org/species/4278104 but that species page doesn't show the issue (or am I missing something?)

**Comment by MortenHofft** [comment]
> content issues that are labelled public relevance is public

It needs to be labeled as having `public relevance`. This is up to the data content team and communications team to decide when to do so. I've done so for the mentioned issue, but I'm not the best person to evaluate and react on content issues. The first version did indeed show all, but it was changed to require validation. The reasoning has been:

* Don't show any and all comments. Not all comments are relevant. And some sort of absue and insult filter was a requirement from the secretariat to protect users and publishers. 

_An experiment_
Basically the feedback system as it is now is an experiment and a hack. We wanted to get of JIRA and have the option for users to make public comments on the data - exactly  as Tony Rees does in https://github.com/gbif/portal-feedback/issues/360 

But a lot of questions remain open. Does it make sense to use Github this way at all. What kind of feedback do we get. Can it be maintained this way. Will country nodes participate (content issues are tagged with the country code of the reporter).  Help desk questions are directed here as well instead of mail. It isn't perfect for any of these, but as we learn more we might be able to tweak it or decide on a different system altogether.
