### ISSUE TITLE
test that rate limits are properly reflected to the user

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#609]
inspired by [this Jira issue](http://dev.gbif.org/issues/browse/POR-2813?jql=project%20%3D%20POR%20AND%20status%20%3D%20Open)

we have a limit on nr of downloads within a timespan. This should be communicated to the user. if too many downloads then fail with an informative error message. Or perhaps inform before trying to start the download

**Comment by MortenHofft** [comment]
@MattBlissett do you know what the rate limits is. Does the API inform me somehow or does it simply fail?

**Comment by MattBlissett** [comment]
A user should be limited to 3 simultaneous downloads: https://github.com/gbif/gbif-configuration/blob/master/occurrence-ws/prod/application.properties#L34

The API should return HTTP 420 when this is exceeded. I've seen that when authenticating as the user using Curl, I'm not certain it happens when submitting downloads as the occdownload/admin user.

**Comment by MortenHofft** [comment]
As far as I can see I just get a 500 back. The website is using the simple GET download option. I'm closing this issue. If we get comments on it we could update the API to return something more informative.

**Comment by MattBlissett** [comment]
I'm opening it, since that's the API not working as intended. I'll look next week.

**Comment by MattBlissett** [comment]
The service will return a response like this if there are too many downloads from one user:

```http
HTTP/1.1 420 420
Date: Wed, 21 Nov 2018 13:26:50 GMT
Content-Type: text/plain
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD, GET, POST, DELETE, PUT
Transfer-Encoding: chunked
Server: Jetty(9.3.z-SNAPSHOT)

Too many simultaneous downloads, please wait for some to complete.

Usually this is too many downloads from a single user, but it can be too many downloads overall.
See your user page, or the GBIF health status page.
```

I can't seem to change the response text (`420 420`).

NB the content type is fixed to `text/plain`, since for a successful GET download request the response looks like this:

```http
HTTP/1.1 200 OK
Date: Wed, 21 Nov 2018 13:26:46 GMT
Content-Type: text/plain
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD, GET, POST, DELETE, PUT
Transfer-Encoding: chunked
Server: Jetty(9.3.z-SNAPSHOT)

0001079-180611120914121
```

I'll leave this open but a portal issue, so we can check the user sees something appropriate after this change.
