### ISSUE TITLE
Support user create and reset password

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#62]
The UI needs to offer account creation and reseting of passwords backed by a Drupal JSON API.

**Comment by MortenHofft** [comment]
Chinese users do currently not have the option to register as Google is blocked and we use a google service to validate for robots. That needs to be solved going forward. Currently we manually help those users that contact us, but others probably just give up.

If I understand correctly this is no longer planned to be a Drupal api endpoint.

**Comment by MortenHofft** [comment]
the front end is in place for this, but needs testing once the backend supports it

**Comment by kbraak** [comment]
@MortenHofft IMHO this issue should be labelled as a release blocker because this login functionality is fundamental.

**Comment by MortenHofft** [comment]
Hi @kbraak thanks. I've noticed you have left that comment many places. And you are right.
Yes it is of obviously a release blocker for closing down the current site and switching over. 

The `release blocker` tag was used to indicate what had to be done, not to replace the existing site, but for for it to be available for a release for more public stress testing. And since we won't be creating accounts in two systems, this was not considered a blocker.

But there is no way you could know that from the tag alone. Sorry about that. 

It was intended as a general tag to cover "the next release" what ever that is at a certain point in time. In half a year, `release blocker` might be "insufficient help text"  if we consider that the goal of the release - that at least was how it was intended. Thanks
