### ISSUE TITLE
feature request: home page preview

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal16#621]
Is is possible to have a preview function for the home page content type in Contentful? So as with the other types, load and show the current draft of the homepage?

**Comment by MortenHofft** [comment]
It is of course doable, but the data on that page comes from the elastic search index (search for latest news fx). And that doesn't operate with a draft and a published version. So to do that would currently require a draft ES index (then search could also be tested) or we could rewrite the homepage to query contentful directly instead of using the search we already have (that seems like a bad solution to me). Alternatively we could say that UAT is always a draft index and draft view. Then UAT would always show the drafts of all content.

**Comment by dnoesgaard** [comment]
Not all data, I suppose? E.g. the header image and features aren't loaded from the index, right?

**Comment by MortenHofft** [comment]
nope not all - it is a mixture

**Comment by dnoesgaard** [comment]
I would be happy with a preview function that reflected non-index content only.

(explainer: I mostly need it to verify that header images look ok)

**Comment by MortenHofft** [comment]
Makes sense. I'll add it as ?_isPreview since the normal convention won't work for the home page (it would then be another url).

**Comment by dnoesgaard** [comment]
Cool, thanks.

So the url would be https://www.gbif.org/?_preview 
?

**Comment by MortenHofft** [comment]
yes

**Comment by dnoesgaard** [comment]
sweet - added to Contentful

**Comment by MortenHofft** [comment]
Please reopen if it isn't what you imagined
