### ISSUE TITLE
Occurrence search: Taxon filter should link synonyms to their accepted name

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal16#622]
When a synonym name is selected from the taxon filter, we currently only show occurrences with this name usage, not all all occurrences of the taxon.
However, when an accepted taxon is selected, all occurrences regardless of name usage is shown.

An example:
1.  Boletus satanas -> 388 occurrences
2. Rubroboletus satanas -> 603 occurrences
3. Suillellus satanas -> 991 occurrences

Since nr 1 and 2 are synonyms of 3, they should also return 991 occurrences, and preferably indicate the synonym status.

Then we will show occurrences of a Taxon as opposed to occurrences of a name usage of a Taxon.

**Screenshot showing the problem:**
![rubro_satanas](https://user-images.githubusercontent.com/1666484/31882627-ae08de82-b7e7-11e7-82e4-adf1da639ff6.png)

**Screenshot of proposed solution:**
![solution_synonyms](https://user-images.githubusercontent.com/1666484/31882644-bcac3b3c-b7e7-11e7-9392-2397af67fc1c.png)

**Comment by MortenHofft** [comment]
Doesn't it make sense to show the synonym only count and instead a notification of it being a synonym. this seem more similar at least to the way we handle data on species pages of synonyms (where we show a map with the synonym usage only fx)

**Comment by MortenHofft** [comment]
@thomasstjerne This have an unfortunate side effect as seen in this issue: https://github.com/gbif/portal-feedback/issues/630

The problem is that the synonym in this case is a subspecies and searching for that taxonKey won't include the original (synonym) records since occurrence index don't have subspeciesKeys. So the user cannot download the data unless they go to the parent species (which of course might be more than what they want)

It also creates a strange behaviour in search where it says ≈3000 results, but when clicking you get 0. But even if fixed it would be another number since it redirects. If we redirect we should make sure the numbers align with search and other places as well.

I'm not sure how to best do this, but I'm tempted to revert at this point. And then wait for the occurrence index to support it. Or only redirect when it is to species and above. Or only suggest a redirect.

**Comment by MortenHofft** [comment]
https://www.gbif.org/species/3039489 fx shows 0 occurrences in GBIF
but in fact the API shows that there are 2695
http://api.gbif.org/v1/occurrence/search?taxonKey=3039489

Meaning that our APIs aren't constructed such that we can simply replace a taxonKey with its accepted key

**Comment by MortenHofft** [comment]
I've reverted
https://github.com/gbif/portal16/commit/a4d1287928f8146bc03111d64eb5722255b50e30
and 
https://github.com/gbif/portal16/commit/ec64b4842aaa80642af0a706812b178aeb024e12

It isn't ideal either. Lets discuss how to approach it when you are back @thomasstjerne

**Comment by thomasstjerne** [comment]
Seems that this is issue has been discussed before. Theres an extended discussion [here](http://dev.gbif.org/issues/browse/POR-1984)

**Comment by MortenHofft** [comment]
Let us revive this issue once again

Reading this again I do not understand why there was an issue with subspecies I must admit. But I would be nice to understand before taking this on again.

I suggest to do

**Step 1**
Showing a warning if a user selects a not accepted name. 
```
[x] Felix concolor
The accepted name is Puma concolor, do you widh to search for this instead.
YES/NO
```

This is useful and educates the user (or at least tell them what the backbone believes) and will not break anything as far as I can see. No automatic redirects. And it will also work for links where the search parameters is defined in the URL.

**Step 2**
To complement this we could consider a toggle on search (it could be active by default), that restricts results to accepted names.
I enter `Felis con    ` and I see the suggestion
```
Puma concolor
Accepted name for Felis concolor
```

This saves me the extra reading and clicking YES (as is needed in "step 1"). To do this it would be nice if the suggest could include information on the accepted species. As an optional param on the suggest perhaps to avoid bloating the response size?

**Comment by mdoering** [comment]
Both great ideas @MortenHofft !
Being able to search by a synonym name only has also advantages. If we would always return all occurrences for all names sharing the same accepted name we would not be able to filter them on their name which can be useful at times.

**Comment by MortenHofft** [comment]
On the hosted portals we currently add a little warning dot with a hover text. It isn't ideal either, but at least it indicates that there might be something to consider. We could consider that a `step 0` in above. 

<img width="346" alt="Screenshot 2021-05-06 at 15 35 12" src="https://user-images.githubusercontent.com/6759267/117308498-e15e4d00-ae81-11eb-8ced-debf453431bc.png">

It is a hover simply because spelling it out created a lot of text and made it difficult to scan the suggestions. At least with my - lacking - design abilities.
