### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#71]
We've considered ideas around:

- A search box
- Summary metrics
- What is GBIF?
- The GBIF Network map (see #70)
- Featured datasets
- News 

- [ ] Guidance for content in comments below
- [ ] Implementation of page v1

**Comment by kcopas** [comment]
@timrobertson100 revised text for home, per Skype discussion earlier this week.

#### Under development

We are now actively engaged in redesigning GBIF.org. This is still an early-access release with limited functionality. The content exposed here is the same as that presented on the current site.

Our first release aims to address issues reported and observed since we launched the current GBIF.org site in October 2013. Most common among these are a subpar search experience and confusing navigation within a large site. 

Significant improvements in our data processing and handling infrastructure now make it possible to introduce site-wide cross-content search, and revisions to the navigation reflect a much leaner site featuring a menu that encapsulates a simpler overall structure.

Thanks for your interest, and your patience: we'll turn on feedback mechanisms to get your comments soon.
