### ISSUE TITLE
Personalisation

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#726]
Personalisation has been discussed on anf off for a while. What is meant and how far should we go. To begin with it is suggested that we write down some ideas and create a few mockups of what a first simple to implement step could be. 

Ideas:

IMPLEMENTED
* [x] trusted contacts on datasets (can see more on crawling and start new ones) IMPLEMENTED

SHOULD START WITH MOCKS
* [x] option to make profile public
* [ ] show (relevant) data from public orcid on profile ? what would be relevant?
* [x] list dataset linked to user email or orcid (dataset/publisher/host contact)
* [x] allow user to self identify with recorder names (though not necessarily unique) to see all my occurrences in GBIF.
* [x] saved occurrence filters
* [ ] notify my if recent downloads have have changed (lots of new data if running the query again) ? Is this at all meaningful/interesting?
* [x] show badges on profile

**Comment by MortenHofft** [comment]
mockup for public option, linked datasets based on orcid/email, self associated recorder names, badges
![profile dashboard](https://user-images.githubusercontent.com/6759267/38684320-b6c8f606-3e6f-11e8-91e5-23dcacf36bbb.jpg)

**Comment by MortenHofft** [comment]
saving filters. Clicking favorites will take you to a list of your favorite filters with the names you gave them. basically a bookmark.

![favourite filters](https://user-images.githubusercontent.com/6759267/38685386-190ef034-3e72-11e8-95e7-39786e4642e3.jpg)

**Comment by kcopas** [comment]
I recently started lists and sketching mockups on this, too.

Other items worth consider, imho, include:

### For all opt-in users
- [ ] ORCID
- [ ] Institutional affiliations
- [ ] Project affiliations (CESP, BID, BIFA)
- [ ] GBIF-related publications (via literature tracking and/or ORCID)
- [ ] GBIF featured data uses

### For network members (esp. node managers)
- [ ] GBIF network and committee roles and assignments
- [ ] GitHub profile/contributions/issues/assigned-issues

### For data holders
- [ ] Dataset stats/metrics, as above—including download activity, too,
perhaps?
- [ ] GitHub profile/issues/assigned-issues

### For biological knowledge experts
- [ ] Described species (long-term: claim via COL+?)

Science ambassadors could introduce other fields, too, in consultation w/
@dschigel

=====
*Kyle Copas*
Skovtoftebakken 15
2830 Virum
(+45) 28 75 14 75 | skype kylecopas

**Comment by kcopas** [comment]
Also, email alerts by dataset or taxa, per ALA:
<img width="677" alt="ala-email-alert" src="https://user-images.githubusercontent.com/12379236/38687719-9a58be7c-3e77-11e8-8d58-78c0af63bad6.png">

Not the greatest example, perhaps—we have no way of ID'ing citizen science records per se—but consider someone with responsibility for monitoring or reporting outbreaks of an invasive species. Tell me when a new record is added for my country.

This may build off the saved filters above.

**Comment by MortenHofft** [comment]
@kcopas that is wonderful. If you have mockups then please share, then someone else than me can decide what brings most value based on those mocks.

**Comment by dschigel** [comment]
Notes that ORCID is a researcher ID system, and they talk about "works" https://support.orcid.org/knowledgebase/articles/462032-add-works-to-your-orcid-record, I propose we think what data activities, roles and product would look more or less natural in the ORCID world, and start from those. I undestood that ORCID definition of works is rather broad, and basically any marginally academic stuff  could be added as long as there is a stable identifier https://support.orcid.org/knowledgebase/articles/462052-add-works-manually

**Comment by dschigel** [comment]
A few additional thoughts:

For GBIF publisher & user behavior:
https://orcid.org/blog/2015/10/26/auto-update-has-arrived-orcid-records-move-next-level

One other example of the benefits and how they are marketed is from Wiley notification I got after an EBV related ms was out:

"Good news! If you used your ORCID iD during submission, you can now choose to update your ORCID record automatically. You will be sent an email by CrossRef, who registers Digital Object Identifiers (DOIs) for research publications, asking to access your ORCID record. Simply grant them permission once and your ORCID record will be updated each time you publish an article with one of their partner journals and publishers (including Wiley)."

Later, an exercise by David Shorthouse made me think that it would be interesting to repeat this with GBIF instead of Taxonomy. I think we will need GBIF as a recommended keyword for the ORCID account holders

from Taxacom
"Yesterday was World Taxonomist Appreciation Day so naturally I asked, "How many active taxonomists are there"? And secondarily, "Where are they & what do they work on?"
Here's the barebones result: http://taxonomists.shorthouse.net/
Not there? Get yourself an ORCID at https://orcid.org, add a keyword "taxonomist" or "taxonomy" and then link your works. Once a day I poll ORCID and fire the titles of your publications through the Global Names Recognition and Discovery service, http://gnrd.globalnames.org/ to glean your taxa of expertise.
Perhaps by next March 19 we can give this a more professional home, have a collective celebration, and use it for something bigger."

**Comment by MortenHofft** [comment]
Closing this as ideas have been generated and condensed by @kcopas . Next step is to decide on which ideas to continue with. I'm thinking that is better done in a new issue, with the selected ideas and priorities

**Comment by kcopas** [comment]
[Summary feature list (180626)](https://github.com/gbif/portal16/files/2252765/feature-list_180626.xlsx), compiled and reviewed (separately) with @MortenHofft @timrobertson100 and @ahahn-gbif , ready for discussions on prioritization and implementation planning.
