### ISSUE TITLE
Suggest a dataset page

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#74]
This is a tool that we can direct to from various places for a user to suggest a dataset that should be in GBIF.  The page should be a form, which when submitted creates an issue in a dedicated GBIF github repository, tagged appropriately.  Content team will then try and mobilise the network to follow up on the suggestion.

Note:  This replaces current Jira issues, and the "Dataset catcher" Google form.

The form should include: 
- URL of the data
- Description
- Type of content (checklist, occurrence etc)
- Country (optional, becomes a tag)
- The users name, email (optional, but if given we'd state that it will be made public)
- Any license on the data (optional, choice of the 3 CC options, but if given a tag is created)

On submission, it simply provides a "thank you" and link to github issue.

- [x] Create github repo called gbif/data-mobilisation and the necessary credentials for the app to post
- [x] Create the form and submission to create the issue
- [x] Make fully translatable
- [ ] On species page, next to map add link "Do you know of datasets that can help fill this map?  Please tell us!"

**Comment by siro1** [comment]
**The users name, email (optional, but if given we'd state that it will be made public)**
 
Better to ask a user whether they would like to have their contact info made public or not instead of saying that if they provide the info we will make it public.  We can certainly make good use of the contact info of the user for private communication without making it public - may be a checkbox on making public or not. New suggestion:

The users name, email (optional, please indicate whether it should be made public on GBIF.org or not)

**Comment by timrobertson100** [comment]
In this instance, I'm afraid not.  On submission the form will create an issue in GitHub which is public and open to viewing.

**Comment by siro1** [comment]
OK, it is my understanding of "public" that makes me think that users might shy away from providing contact info.  Additional info that Github is the "public" place meant might help.

**Comment by MortenHofft** [comment]
We do not have any captcha on the page. That might become important to avoid bots. Let us see what happens, and if so we can add it?

**Comment by kcopas** [comment]
I have edits for text, but this is not Drupal, correct? How shall I share them with you?

I have one other small issue I'm running down with @timhirsch, but meanwhile...

Can I suggest that we add an explicit acceptance of terms statement and check box above the submit button (perhaps as part of a captcha block, if that's implemented) rather than current approach with duplicated field caption 'notice that all information is public'. The revised text alludes to the public nature of the submission, but 'submit' is the normal place to agree to such terms.

**Comment by timrobertson100** [comment]
Please just put text edits in here.

**Comment by kcopas** [comment]
in Markdown already:

Not finding the data you're looking for? Know about datasets you'd expect to see here?

The GBIF network actively strives to fill gaps in the open-access biodiversity data we provide (it's part of our current [strategic plan](http://#), in fact). Users of our tools and services often have expert knowledge about given regions or taxa/species. We welcome your help in identifying other data sources capable of improving the quality, transparency and reproducibility of scientific research and policy supported by GBIF. 

Share what you know about datasets you'd like us to consider adding. Only the first four fields (name, link, region and taxon) are required; all others are optional. In keeping with our commitment to openness, your submission will appear as a GitHub issue [here](http://#), where you and other interested in increasing open access to biodiversity data can follow and add to it. 

For our part, we will work with our network of members and publishers to contact the data holders and explore their interest in publishing their data through GBIF.org.

**Comment by timrobertson100** [comment]
Applied the change to the repository name, and the text in the file.
