### ISSUE TITLE
Revise footer content

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#77]
- [x] Offer proposed text / information in comment below
- [ ] Implement proposal

**Comment by kcopas** [comment]
Propose minimal footer for the EOY release. Could be expanded to include other elements later: candidates might include
+ Sign-up for newsletter
+ Map showing Secretariat location
+ Featured logos of partners, funders, nodes/participants, affiliates et al.

However, Google Analytics data appears to support none of these additional functions—traffic through the current footer links is miniscule. So for now, I'd like propose to a minimalist approach that includes the following:

+ About GBIF
+ [Terms of use](http://www.gbif.org/terms/overview)
+ [Privacy policy](http://www.gbif.org/terms/privacy-policy)
+ [Contact us](http://www.gbif.org/contact/contact-us) **NEEDS UPDATE**
+ Street address and phone # (no fax needed in footer—will appear on revised contact page)
+ Links to social media: 
    + [Twitter](https://twitter.com/GBIF)
    + [Facebook](https://www.facebook.com/gbifnews)
    + [LinkedIn](http://www.linkedin.com/groups/GBIF-55171)
    + [Vimeo](http://vimeo.com/gbif)
    + [YouTube](https://www.youtube.com/user/GBIFvideo)

**Comment by kcopas** [comment]
For the record, I did also consult with Admin about whether any existing footer items needed to be carried over. Most important one is the travel guidelines, but there is no need to keep it in the footer. File just needs to be retrievable via search and (probably) via short URL (we've clearly already got one redirect in place) and find a utilitarian location somewhere else.

**Comment by MortenHofft** [comment]
travel guidelines does show up in search. It needs some attention as it doesn't look nice though. 
https://demo.gbif.org/search?q=travel%20guidelines
the url looks reasonable to me: https://demo.gbif.org/resource/travel-guidelines

**Comment by MortenHofft** [comment]
I have removed the logos from the footer. Those companies seem to be fairly strict about their logo usage. As it was green in the footer that was clashing with their terms of usage.
![screen shot 2017-02-14 at 13 52 05](https://cloud.githubusercontent.com/assets/6759267/22929599/dd726666-f2bc-11e6-9fb4-bf64407ccc42.png)

I think we might also be violating the terms on the share button
guidelines

* [vimeo](https://vimeo.com/about/brand_guidelines)
* [youtube](https://www.youtube.com/yt/brand/using-logo.html)
* [facebook](https://en.facebookbrand.com/assets/f-logo)
* [linkedin](https://brand.linkedin.com/visual-identity/logo)
* [twitter](https://brand.twitter.com/logo)

if using logos it seems it needs to be something along the lines of
![screen shot 2017-02-14 at 13 56 15](https://cloud.githubusercontent.com/assets/6759267/22929735/6f971866-f2bd-11e6-971b-49148490c4ab.png)
no color changing, no circles etc. Going back to plain text seems the easiest.

Notice that we also violate terms on the existing site it seems
![screen shot 2017-02-14 at 13 58 13](https://cloud.githubusercontent.com/assets/6759267/22929780/a851dd12-f2bd-11e6-9564-6bee5ed7d023.png)

**Comment by kcopas** [comment]
I recognize that by failing to take this up earlier, it's languished and has a few elements that have been implemented piecemeal. But I think we need to take a fresh look at it for next week, if at all possible, not least because that piecemeal implementation has led us to miss a few key elements. 

The addition of the privacy policy and data user agreement is important, but it skips the equally important [data publisher agreement](https://demo.gbif.org/terms/data-publisher) (successfully migrated) as well as the miscellaneous [terms of use](http://www.gbif.org/terms/overview) on data, maps and boundaries, and names of countries, territories and islands (not migrated—yet). 

I'll create a mockup proposal ASAP—one that also addresses the social content per above—so that we can implement a consistent footer across all pages, both Contentful and non-Contentful (un-Contentful? dis-Contentful?), prior to next Monday.
