### ISSUE TITLE
Implement the endorsement page

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#81]
The current implementation has the expression of interest forms which have caused some level of annoyance but are referenced in several communications.

We need to decide if we wish to continue in this approach, simplify the form users fill in (perhaps using GitHub issues?) or ask that they just mail GBIF.
- [ ] Decide on the implementation approach
- [ ] Develop solution

**Comment by MortenHofft** [comment]
See also http://dev.gbif.org/issues/browse/POR-2998

**Comment by kbraak** [comment]
In addition to the valuable enhancements listed in [POR-2998](http://dev.gbif.org/issues/browse/POR-2998), I'd like to propose one more based on feedback collected this morning from BGBM. 

After taking plenty of valuable time to fill in the registration form, the submitter canceled their registration because they couldn't confirm the following condition, presented on the last page of the form:

- [ ] I understand that I am seeking registration on behalf of my organization, and confirm that the responsible authorities of my organization are aware of this registration. 

Indeed getting the appropriate permissions can be a long and bureaucratic process. 

To save the valuable time of the submitter, the terms and conditions should be explained much earlier. Perhaps by even making the Terms and Conditions page (see below) the first or second page in the form, an idea proposed by @dschigel. 

![screen shot 2017-01-12 at 11 41 14](https://cloud.githubusercontent.com/assets/5981100/21886901/f6fcd666-d8bd-11e6-8ee0-0687fe9a7440.png)

**Comment by kbraak** [comment]
@burkeker @siro1 
Request captured from NSG meeting: form should include field to capture project name or project identifier that the organization is participating in, e.g. BID.  This information will then get passed on to the endorsing node manager giving them better context about the organization's request.

**Comment by dschigel** [comment]
Good point, makes more practical to do the next steps. I do hope that the web form stays as short as possible with a little obligatory fields as possible. The information is often seen from from the e-mail address of the dataset contact - .dk, .nl etc, but not always.

**Comment by timrobertson100** [comment]
I'd also encourage trying to make this as accessible and easy to complete as possible - minimal required fields.  As an example, Kyle comments about a user being scared off from this:

- [ ] I understand that I am seeking registration on behalf of my organization, and confirm that the responsible authorities of my organization are aware of this registration.

This could be made more approachable by removing some formality and giving clear explanatory text. For example we could include information that 1) the information is primarily used in citations and metrics and therefore should be a sensible department or unit name, 2) good examples would include "The University of Glasgow, Department of Zoology", "CSIRO Department of Environment" etc and 3) that the information provided can be changed at any time through helpdesk@gbif.org.  We always have the ability to remove datasets and change attributions if there are issues.

**Comment by siro1** [comment]
Good suggestions: 
timrobertson100's explanatory text could go into the guidelines here http://www.gbif.org/publishing-data/endorsement#criteria instead of going into the form itself. We can revise the relevant section.

**Comment by dagendresen** [comment]
Norwegian organisations signing up using the request endorsement form often wants to revisit and update their description after they see how it looks like in the GBIF portal. Possibilities for the contacts persons from the data publishing organisations to login and update their own description as is displayed in the GBIF portal would be welcome.

**Comment by timrobertson100** [comment]
Thanks @dagendresen .  Would you like to see this in the hands of the organisation owners themselves, or managed by the national node staff please?  I could imagine the best approach might be that initial creation needs to be vetted by the Node to ensure some level of consistency, but after that editing by the organisation staff would be sensible.  When we've had open registration in the past it has resulted in a mess with many duplicates, and inconsistencies where departments are shown as organisations etc.
