### ISSUE TITLE
Enhance programme and project pages

### ISSUE THREAD

**Issue by timrobertson100** [gbif/portal16#93]
This issue serves as a placeholder for enhancement ideas for the programme and project pages. 

It is likely these enhancements won't be implemented until early 2017, but we should capture the requirements as we can.  @melianieraymond is the best person to describe these.  The general intention is to help showcase all the activity undertaken; one audience being to demonstrate to funders capacity enhancement. 

Note: these should include historical artifacts so that these can be used in e.g. future grant applications to demonstrate that it is building on previous work. We also invite Participants to browse past projects to get inspiration for new project proposals.

The entities and ideas to consider are
- [ ] Events (list participants and include photos - consider modeling people, or just listing as text)
- [ ] Reports produced
- [ ] Datasets mobilised
- [ ] News items
- [ ] Training material
- [ ] Translated content (could be any of above)

A fairly complete example is http://www.gbif.org/project/2015-lusophone-africa.

Note also that the people involved in the project can use these as a "mini website" to showcase their effort and build capacity. We have received requests from the francophone community to contribute French translations of the text on the project page to make it easier for them to use them.

**Comment by MortenHofft** [comment]
Many of these has since been covered in one form or another.

datasets and news&events have a seperate tab now.
https://www.gbif.org/project/82729/mobilizing-biodiversity-data-from-the-forest-reserves-of-southern-and-central-benin

photos and reports and translated material is highlighted links
https://www.gbif.org/project/82703/mobilization-of-biodiversity-data-on-protected-areas-and-threatened-species-in-benin

As for translations, the page can be translated and materials can be uploaded in several languages

browsing past projects can be done by
https://www.gbif.org/programme/82243/bid-biodiversity-information-for-development#projects
or 
https://www.gbif.org/resource/search?contentType=project

**Comment by MortenHofft** [comment]
I'm closing this as things have changed a lot since that initial implementation and Maheva have been giving extensive feedback, suggested changes and signed it of.

Please reopen as necessary
